name: CI
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.5.3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Run the test suite
        run: flutter test
